zz

diff --git a/.github/workflows/AlgoSecCodeAnalysis.yaml b/.github/workflows/AlgoSecCodeAnalysis.yaml
--- a/.github/workflows/AlgoSecCodeAnalysis.yaml
+++ b/.github/workflows/AlgoSecCodeAnalysis.yaml
@@ -105,18 +105,17 @@ jobs:
       - name: Terraform Plan
         if: steps.init.outputs.exitcode == 0 && steps.validate.outputs.exitcode == 0
         id: plan
-        run: terraform plan -input=false -no-color -out=tf.out
+        run: terraform plan -input=false -no-color -out=/tmp/tf.out
         continue-on-error: true
 
       - name: Terraform Convert Plan to JSON
         if: steps.init.outputs.exitcode == 0 && steps.validate.outputs.exitcode == 0 && steps.plan.outputs.exitcode == 0
         id: plan_to_json
-        run: terraform show -json /tmp/tf.out > tf.json.out
+        run: terraform show -json /tmp/tf.out > /tmp/tf.json.out
         continue-on-error: true
 
       - name: Terraform Status
         id: status
-        # shell: bash
         run: |
           init_status=${{ steps.init.outputs.exitcode }}
           validate_status=${{ steps.validate.outputs.exitcode }}
@@ -127,173 +126,158 @@ jobs:
           # Check the teraform's init, validate and plan steps and initialize terraform_output and terraform_err environment variables
           then
             echo "Error in init step. Exit code $init_status."
-            echo 'terraform_stderr<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.init.outputs.stderr }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
-            echo 'terraform_stdout<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.init.outputs.stdout }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
+            >&2 echo "${{ steps.init.outputs.stderr }}"
+            echo "${{ steps.init.outputs.stdout }}"
           elif [[ $validate_status -ne 0 ]]
           then
             echo "Error in validate step. Exit code $validate_status."
-            echo 'terraform_stderr<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.validate.outputs.stderr }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
-            echo 'terraform_stdout<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.validate.outputs.stdout }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
+            >&2 echo "${{ steps.validate.outputs.stderr }}"
+            echo "${{ steps.validate.outputs.stdout }}"
           elif [[ $plan_status -ne 0 ]]
           then
             echo "Error in plan step. Exit code $plan_status."
-            echo 'terraform_stderr<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.plan.outputs.stderr }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
-            echo 'terraform_stdout<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.plan.outputs.stdout }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
+            >&2 echo "${{ steps.plan.outputs.stderr }}"
+            echo "${{ steps.plan.outputs.stdout }}"
           else
             echo "Terraform phase was completed successfully."
-            echo 'terraform_stdout<<EOF' >> $GITHUB_ENV
-            echo "${{ steps.plan.outputs.stdout }}" >> $GITHUB_ENV
-            echo 'EOF' >> $GITHUB_ENV
+            echo "${{ steps.plan.outputs.stdout }}"
           fi
 
-          echo "Complete step with exit code ${status}"
           echo "::set-output name=exitcode::${status}"
 
       - name: Echo status
         run: |
           echo "Terraform running status ${{ steps.status.outputs.exitcode }}"
-          echo "Terraform running stderr ${{ env.terraform_stderr }}"
-          echo "Terraform running stdout ${{ env.terraform_stdout }}"
+          echo "Terraform running stderr ${{ steps.status.outputs.stderr }}"
+          echo "Terraform running stdout ${{ steps.status.outputs.stdout }}"
 
       ################################ Aws steps ################################
-      - name: Generate uuid for tmp file name
-        if: steps.status.outputs.exitcode == 0
-        id: generate-uuid
-        uses: filipstefansson/uuid-action@v1
-        with:
-          name: ${{ github.sha }}
+      # - name: Generate uuid for tmp file name
+      #   if: steps.status.outputs.exitcode == 0
+      #   id: generate-uuid
+      #   uses: filipstefansson/uuid-action@v1
+      #   with:
+      #     name: ${{ github.sha }}
 
-      - name: Copy tmp file into S3
-        if: steps.status.outputs.exitcode == 0
-        run: |
-          cat tf.json.out
-          aws s3 cp tf.json.out s3://vitalylanda-test/github-codeanalysis/tmp${{ steps.generate-uuid.outputs.uuid }}.out --metadata customer=${{ github.repository_owner }},action_id=${{ steps.generate-uuid.outputs.uuid }}
+      # - name: Copy tmp file into S3
+      #   if: steps.status.outputs.exitcode == 0
+      #   run: |
+      #     cat /tmp/tf.json.out
+      #     aws s3 cp /tmp/tf.json.out s3://vitalylanda-test/github-codeanalysis/tmp${{ steps.generate-uuid.outputs.uuid }}.out --metadata customer=${{ github.repository_owner }},action_id=${{ steps.generate-uuid.outputs.uuid }}
 
-      - name: Wait till analysis complete
-        if: steps.status.outputs.exitcode == 0
-        id: analysis_status
-        shell: bash
-        run: |
-          for(( i=1; i<=10; i++ ))
-          do
-            output=$(curl -s "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response?customer=${{ github.repository_owner }}&action_id=${{ steps.generate-uuid.outputs.uuid }}");
-            status=$(echo $output | jq -r '.message_found');
-            if [ $status = "true" ]
-              then
-                result=$(echo $output | jq -r '.result');
-                echo "full result: $result"
-                result_success=$(echo $result | jq -r '.success')
-                echo "sucess: $result_success"
-                additions=$(echo $result | jq -r '.additions')
-                echo "additions: $additions"
-                analysis_state=$(cat output.txt | jq -r '.analysis_state')
-                echo "analysis state: $analysis_state"
-                analysis_result = ${result_success} && $analysis_state
-                break
-              else
-                echo "The result is not ready yet" 
-                sleep 30
-            fi
-          done
+      # - name: Wait till analysis complete
+      #   if: steps.status.outputs.exitcode == 0
+      #   id: analysis_status
+      #   shell: bash
+      #   run: |
+      #     for(( i=1; i<=10; i++ ))
+      #     do
+      #       output=$(curl -s "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response?customer=${{ github.repository_owner }}&action_id=${{ steps.generate-uuid.outputs.uuid }}");
+      #       status=$(echo $output | jq -r '.message_found');
+      #       if [ $status = "true" ]
+      #         then
+      #           result=$(echo $output | jq -r '.result');
+      #           echo "full result: $result"
+      #           result_success=$(echo $result | jq -r '.success')
+      #           echo "sucess: $result_success"
+      #           additions=$(echo $result | jq -r '.additions')
+      #           echo "additions: $additions"
+      #           analysis_state=$(cat output.txt | jq -r '.analysis_state')
+      #           echo "analysis state: $analysis_state"
+      #           analysis_result = ${result_success} && $analysis_state
+      #           break
+      #         else
+      #           echo "The result is not ready yet" 
+      #           sleep 30
+      #       fi
+      #     done
 
-          if [ $status = "true" && $analysis_result = "true" ]
-            then
-              exit_code=0
-              out = "The analysis process was completed successfully"
-              if [ -z $additions ]
-                out = $out'\n'$additions
-              echo "::set-output name=stdout::${out}"
-            else
-              exit_code=1
-              echo "::set-output name=stderr::$(printf "The analysis process failed.\nWith additional information: $additions\n")"
-          fi
+      #     if [ $status = "true" && $analysis_result = "true" ]
+      #       then
+      #         exit_code=0
+      #         out = "The analysis process was completed successfully"
+      #         if [ -z $additions ]
+      #           out = $out'\n'$additions
+      #         echo "::set-output name=stdout::${out}"
+      #       else
+      #         exit_code=1
+      #         echo "::set-output name=stderr::$(printf "The analysis process failed.\nWith additional information: $additions\n")"
+      #     fi
 
-          echo "::set-output name=exitcode::${exit_code}"
-          echo "::set-output name=report::${additions}"
+      #     echo "::set-output name=exitcode::${exit_code}"
+      #     echo "::set-output name=report::${additions}"
 
-          exit $exit_code
-        continue-on-error: true
+      #     exit $exit_code
+      #   continue-on-error: true
 
-      ################################ Update PR and complete the job ################################
-      - name: Comment on PR
-        # update Pull Request by the operation status
-        uses: actions/github-script@v5
-        env:
-          terraform_status: ${{ steps.status.outputs.exitcode }}
-          analysis_status: ${{ steps.analysis_status.outputs.exitcode}}
-          analysis_out: ${{ steps.analysis_status.outputs.stdout}}
-          analysis_err: ${{ steps.analysis_status.outputs.stderr}}
-          analysis_report: ${{ steps.analysis_status.outputs.report}}
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const CODE_BLOCK = '```';
-            const terraform_result = '${ process.env.terraform_status } == 0 ' ? ':heavy_check_mark:' : ':x:';
-            const analysis_result = '${ process.env.analysis_status } == 0' ? ':heavy_check_mark:' : ':x:';
+      # ################################ Update PR and complete the job ################################
+      # - name: Comment on PR
+      #   # update Pull Request by the operation status
+      #   uses: actions/github-script@v5
+      #   env:
+      #     terraform_status: ${{ steps.status.outputs.exitcode }}
+      #     analysis_status: ${{ steps.analysis_status.outputs.exitcode}}
+      #     analysis_out: ${{ steps.analysis_status.outputs.stdout}}
+      #     analysis_err: ${{ steps.analysis_status.outputs.stderr}}
+      #     analysis_report: ${{ steps.analysis_status.outputs.report}}
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const CODE_BLOCK = '```';
+      #       const terraform_result = '${ process.env.terraform_status } == 0 ' ? ':heavy_check_mark:' : ':x:';
+      #       const analysis_result = '${ process.env.analysis_status } == 0' ? ':heavy_check_mark:' : ':x:';
 
-            const output = `
-            ### ${ interraform_result } Terraform Processing ⚙️
-            <details><summary>Terraform Log</summary>
-            Output
+      #       const output = `
+      #       ### ${ interraform_result } Terraform Processing ⚙️
+      #       <details><summary>Terraform Log</summary>
+      #       Output
 
-            ${ CODE_BLOCK }
-            ${{ env.terraform_stdout }}
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${{ env.terraform_stdout }}
+      #       ${ CODE_BLOCK }
 
-            Errors
+      #       Errors
 
-            ${ CODE_BLOCK }
-            ${{ env.terraform_stderr }}
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${{ env.terraform_stderr }}
+      #       ${ CODE_BLOCK }
 
-            </details> <!-- End Format Logs -->
+      #       </details> <!-- End Format Logs -->
 
-            ###  ${ analysis_result }: Code Analysis 🎨
-            <details><summary>Logs</summary>
-            Output
+      #       ###  ${ analysis_result }: Code Analysis 🎨
+      #       <details><summary>Logs</summary>
+      #       Output
 
-            ${ CODE_BLOCK }
-            ${ process.env.analysis_out }
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.analysis_out }
+      #       ${ CODE_BLOCK }
 
-            Errors
+      #       Errors
 
-            ${ CODE_BLOCK }
-            ${ process.env.analysis_err }
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.analysis_err }
+      #       ${ CODE_BLOCK }
 
-            ${ process.env.analysis_report }
+      #       ${ process.env.analysis_report }
 
-            </details>
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+      #       </details>
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
 
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
 
-      - name: Check Teraform results
-        shell: bash
-        run: |
-          echo init ${{ steps.init.outputs.exitcode }}
-          test ${{ steps.init.outputs.exitcode }} -eq 0
-          echo validate ${{ steps.validate.outputs.exitcode }}
-          test ${{ steps.validate.outputs.exitcode }} -eq 0
-          echo plan ${{ steps.plan.outputs.exitcode }}
-          test ${{ steps.plan.outputs.exitcode }} -eq 0
-          echo analysis ${{ steps.analysis_status.outputs.exitcode }}
-          test ${{ steps.analysis_status.outputs.exitcode }} -eq 0
+      # - name: Check Teraform results
+      #   shell: bash
+      #   run: |
+      #     echo init ${{ steps.init.outputs.exitcode }}
+      #     test ${{ steps.init.outputs.exitcode }} -eq 0
+      #     echo validate ${{ steps.validate.outputs.exitcode }}
+      #     test ${{ steps.validate.outputs.exitcode }} -eq 0
+      #     echo plan ${{ steps.plan.outputs.exitcode }}
+      #     test ${{ steps.plan.outputs.exitcode }} -eq 0
+      #     echo analysis ${{ steps.analysis_status.outputs.exitcode }}
+      #     test ${{ steps.analysis_status.outputs.exitcode }} -eq 0
