enable all steps

diff --git a/.github/workflows/AlgoSecCodeAnalysis.yaml b/.github/workflows/AlgoSecCodeAnalysis.yaml
--- a/.github/workflows/AlgoSecCodeAnalysis.yaml
+++ b/.github/workflows/AlgoSecCodeAnalysis.yaml
@@ -2,6 +2,7 @@ name: AlgoSec Action
 on: [pull_request]
 env:
   S3_DEST: devsecops-dev/github-codeanalysis
+  API_URL: "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response"
 jobs:
   changedfiles:
     runs-on: ubuntu-latest
@@ -88,34 +89,6 @@ jobs:
         with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      # - name: Terraform Fmt
-      #   id: fmt
-      #   run: terraform fmt -check -diff
-      #   continue-on-error: true
-
-      # - name: Terraform Init
-      #   id: init
-      #   run: terraform init -no-color
-      #   continue-on-error: true
-
-      # - name: Terraform Validate
-      #   if: steps.init.outcome != 'failure'
-      #   id: validate
-      #   run: terraform validate -no-color
-      #   continue-on-error: true
-
-      # - name: Terraform Plan
-      #   if: steps.init.outputs.exitcode == 0 && steps.validate.outputs.exitcode == 0
-      #   id: plan
-      #   run: terraform plan -input=false -no-color -out=/tmp/tf.out
-      #   continue-on-error: true
-
-      # - name: Terraform Convert Plan to JSON
-      #   if: steps.init.outputs.exitcode == 0 && steps.validate.outputs.exitcode == 0 && steps.plan.outputs.exitcode == 0
-      #   id: plan_to_json
-      #   run: terraform show -json /tmp/tf.out
-      #   continue-on-error: true
-
       - name: Terraform Run
         id: terraform_run
         shell: bash
@@ -183,117 +156,119 @@ jobs:
         if: steps.status.outputs.exitcode == 0
         run: |
           cat /tmp/tf.json.out
-      #     aws s3 cp /tmp/tf.json.out s3://${{env.S3_DEST}}/tmp${{ steps.generate-uuid.outputs.uuid }}.out --metadata customer=${{ github.repository_owner }},action_id=${{ steps.generate-uuid.outputs.uuid }}
+          aws s3 cp /tmp/tf.json.out s3://${{env.S3_DEST}}/tmp${{ steps.generate-uuid.outputs.uuid }}.out --metadata customer=${{ github.repository_owner }},action_id=${{ steps.generate-uuid.outputs.uuid }}
 
-      # - name: Wait till analysis complete
-      #   if: steps.status.outputs.exitcode == 0
-      #   id: analysis_status
-      #   shell: bash
-      #   run: |
-      #     for(( i=1; i<=10; i++ ))
-      #     do
-      #       output=$(curl -s "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response?customer=${{ github.repository_owner }}&action_id=${{ steps.generate-uuid.outputs.uuid }}");
-      #       status=$(echo $output | jq -r '.message_found');
-      #       if [ $status = "true" ]
-      #         then
-      #           result=$(echo $output | jq -r '.result');
-      #           echo "full result: $result"
-      #           result_success=$(echo $result | jq -r '.success')
-      #           echo "sucess: $result_success"
-      #           additions=$(echo $result | jq -r '.additions')
-      #           echo "additions: $additions"
-      #           analysis_state=$(cat output.txt | jq -r '.analysis_state')
-      #           echo "analysis state: $analysis_state"
-      #           analysis_result = ${result_success} && $analysis_state
-      #           break
-      #         else
-      #           echo "The result is not ready yet" 
-      #           sleep 30
-      #       fi
-      #     done
+      - name: Wait till analysis complete
+        if: steps.status.outputs.exitcode == 0
+        id: analysis_status
+        shell: bash
+        run: |
+          for(( i=1; i<=10; i++ ))
+          do
+            output=$(curl -s "${{env.API_URL}}?customer=${{ github.repository_owner }}&action_id=${{ steps.generate-uuid.outputs.uuid }}");
+            status=$(echo $output | jq -r '.message_found');
+            if [ $status = "true" ]
+              then
+                result=$(echo $output | jq -r '.result');
+                echo "full result: $result"
+                result_success=$(echo $result | jq -r '.success')
+                echo "sucess: $result_success"
+                additions=$(echo $result | jq -r '.additions')
+                echo "additions: $additions"
+                analysis_state=$(cat output.txt | jq -r '.analysis_state')
+                echo "analysis state: $analysis_state"
+                analysis_result = ${result_success} && $analysis_state
+                break
+              else
+                echo "The result is not ready yet" 
+                sleep 30
+            fi
+          done
 
-      #     if [ $status = "true" && $analysis_result = "true" ]
-      #       then
-      #         exit_code=0
-      #         out = "The analysis process was completed successfully"
-      #         if [ -z $additions ]
-      #           out = $out'\n'$additions
-      #         echo "::set-output name=stdout::${out}"
-      #       else
-      #         exit_code=1
-      #         echo "::set-output name=stderr::$(printf "The analysis process failed.\nWith additional information: $additions\n")"
-      #     fi
+          if [ $status = "true" && $analysis_result = "true" ]
+            then
+              exit_code=0
+              out = "The analysis process was completed successfully"
+              if [ -z $additions ]
+                out = $out'\n'$additions
+              echo "::set-output name=stdout::${out}"
+            else
+              exit_code=1
+              echo "::set-output name=stderr::$(printf "The analysis process failed.\nWith additional information: $additions\n")"
+          fi
 
-      #     echo "::set-output name=exitcode::${exit_code}"
-      #     echo "::set-output name=report::${additions}"
+          echo "::set-output name=exitcode::${exit_code}"
+          echo "::set-output name=report::${additions}"
 
-      #     exit $exit_code
-      #   continue-on-error: true
+          exit $exit_code
+        continue-on-error: true
 
-      # ################################ Update PR and complete the job ################################
-      # - name: Comment on PR
-      #   # update Pull Request by the operation status
-      #   uses: actions/github-script@v5
-      #   env:
-      #     terraform_status: ${{ steps.status.outputs.exitcode }}
-      #     analysis_status: ${{ steps.analysis_status.outputs.exitcode}}
-      #     analysis_out: ${{ steps.analysis_status.outputs.stdout}}
-      #     analysis_err: ${{ steps.analysis_status.outputs.stderr}}
-      #     analysis_report: ${{ steps.analysis_status.outputs.report}}
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     script: |
-      #       const CODE_BLOCK = '```';
-      #       const terraform_result = '${ process.env.terraform_status } == 0 ' ? ':heavy_check_mark:' : ':x:';
-      #       const analysis_result = '${ process.env.analysis_status } == 0' ? ':heavy_check_mark:' : ':x:';
+      ################################ Update PR and complete the job ################################
+      - name: Comment on PR
+        # update Pull Request by the operation status
+        uses: actions/github-script@v5
+        env:
+          terraform_status: ${{ steps.terraform_run.outputs.exitcode }}
+          terraform_out: ${{ steps.terraform_run.outputs.stdout }}
+          terraform_err: ${{ steps.terraform_run.outputs.stderr }}
+          analysis_status: ${{ steps.analysis_status.outputs.exitcode}}
+          analysis_out: ${{ steps.analysis_status.outputs.stdout}}
+          analysis_err: ${{ steps.analysis_status.outputs.stderr}}
+          analysis_report: ${{ steps.analysis_status.outputs.report}}
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const CODE_BLOCK = '```';
+            const terraform_result = '${ process.env.terraform_status } == 0 ' ? ':heavy_check_mark:' : ':x:';
+            const analysis_result = '${ process.env.analysis_status } == 0' ? ':heavy_check_mark:' : ':x:';
 
-      #       const output = `
-      #       ### ${ interraform_result } Terraform Processing ⚙️
-      #       <details><summary>Terraform Log</summary>
-      #       Output
+            const output = `
+            ### ${ interraform_result } Terraform Processing ⚙️
+            <details><summary>Terraform Log</summary>
+            Output
 
-      #       ${ CODE_BLOCK }
-      #       ${{ env.terraform_stdout }}
-      #       ${ CODE_BLOCK }
+            ${ CODE_BLOCK }
+            ${{ env.terraform_out }}
+            ${ CODE_BLOCK }
 
-      #       Errors
+            Errors
 
-      #       ${ CODE_BLOCK }
-      #       ${{ env.terraform_stderr }}
-      #       ${ CODE_BLOCK }
+            ${ CODE_BLOCK }
+            ${{ env.terraform_stderr }}
+            ${ CODE_BLOCK }
 
-      #       </details> <!-- End Format Logs -->
+            </details> <!-- End Format Logs -->
 
-      #       ###  ${ analysis_result }: Code Analysis 🎨
-      #       <details><summary>Logs</summary>
-      #       Output
+            ###  ${ analysis_result }: Code Analysis 🎨
+            <details><summary>Logs</summary>
+            Output
 
-      #       ${ CODE_BLOCK }
-      #       ${ process.env.analysis_out }
-      #       ${ CODE_BLOCK }
+            ${ CODE_BLOCK }
+            ${ process.env.analysis_out }
+            ${ CODE_BLOCK }
 
-      #       Errors
+            Errors
 
-      #       ${ CODE_BLOCK }
-      #       ${ process.env.analysis_err }
-      #       ${ CODE_BLOCK }
+            ${ CODE_BLOCK }
+            ${ process.env.analysis_err }
+            ${ CODE_BLOCK }
 
-      #       ${ process.env.analysis_report }
+            ${ process.env.analysis_report }
 
-      #       </details>
-      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+            </details>
+            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
 
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: output
-      #       })
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
 
-      # - name: Check Teraform results
-      #   shell: bash
-      #   run: |
-      #     echo terraform state: ${{ steps.status.outputs.exitcode }}
-      #     test ${{ steps.plan.outputs.exitcode }} -eq 0
-      #     echo analysis state: ${{ steps.analysis_status.outputs.exitcode }}
-      #     test ${{ steps.analysis_status.outputs.exitcode }} -eq 0
+      - name: Check Teraform results
+        shell: bash
+        run: |
+          echo terraform state: ${{ steps.status.outputs.exitcode }}
+          test ${{ steps.plan.outputs.exitcode }} -eq 0
+          echo analysis state: ${{ steps.analysis_status.outputs.exitcode }}
+          test ${{ steps.analysis_status.outputs.exitcode }} -eq 0
